name: pages

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install uv"
        uses: astral-sh/setup-uv@v2
        with:
          version: 0.4.7
      - name: "Set up Python"
        run: uv python install
      - name: Install
        run: uv sync
      - name: Sphinx build
        run: "( cd doc && uv run make html )"
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: doc/_build/html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
